---
title: "User Guide"
author: "EPAR"
output:
  html_fragment:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=FALSE)
```

### Overview

The Cambodia Agriculture Survey Data Explorer is a utility for policy analysis, progress tracking, comparison, and reporting. It is designed to be extensively user-modifiable so that commonly used graphics can be quickly regenerated from a new data release, reducing the time between collection and analysis. A public version of the app is available [https://evans-par.shinyapps.io/agquery](here) and can be used to immediately access the data and produce visualizations. The next section will explain how to download your own copy in order to make best use of these features, and the following sections will provide an instructions on using and updating the content in each tab.

This app is built using Posit's R Shiny framework. More information on Shiny can be found [https://shiny.posit.co/r/getstarted/shiny-basics/lesson1/](here)

### Accessing the App: Online vs Offline Access

To take full advantage of the features of the app, it is necessary to either run your own copy locally or host your own instance using your own server framework or the shinyapps.io service. 

#### Requirements for downloading and running a local copy

-   First time R users: download and install [R](https://cran.rstudio.com/) and [RStudio.](https://posit.co/download/rstudio-desktop/)
-   Existing R users: ensure you are running R version 4.4.2 and download RStudio if needed.
-   Download the latest release at the [Git repository](https://github.com/EvansSchoolPolicyAnalysisAndResearch/50x30_AQP).
-   Follow the instructions in the repository readme to finish first time setup. After setup is complete, run the app on your computer by opening the R project and the app.R files in RStudio and pressing the "run app" button that appears in the top right-hand corner of the file pane.

#### Requirements for Self-Hosting

The app can be self-hosted on a server using Docker. Install Docker on your server, clone the directory from github, and build using the included Dockerfile.

### Updating the App

To make your own updates to the app. 

#### Directory Layout

|                 |                                                                                                           |
|--------------------------------------------------------|----------------|
| └── agquery/    |                                                                                                           |
| ├── Data        | *Processed survey data*                                                                                   |
| ├── Extdata     | *Externally sourced data, e.g. World Bank Development indicator CSV files*                                |
| ├── Commodities | *User-defined folders for data/images related to particular agricultural commodities*                     |
| └── World Bank  | *Datasets sourced from the World Bank for display in value boxes on the Economics tab*                    |
| ├── renv        | *Project R package library*                                                                               |
| ├── Scripts     | *Additional code required by the app, includes functions for processing data and creating charts*         |
| ├── Spatial     | *Spatial information (rasters and shapefiles) for maps*                                                   |
| ├── Update      | *Metadata for the survey data folder; update the files in here to change the policy goals and variables.* |
| ├── User Guide  | *Files related to this guide*                                                                             |
| └── www         | *Additional files used in web pages*                                                                      |

### Adding Your Own Data

Additional data can be added to the app by placing CSV files with raw data in the Data subfolder. The following requirements must be met for data files to be usable by the app:

-   The file name must be "Cambodia_CAS\_{YEAR}\_{UNIQUENAME}.csv. The unique name must be consistent across survey years.
-   The files must contain the **ID variables** "hhid", "province", and "zone"
-   Variables in the data files can be named with a combination of letters, numbers, and underscores. They should not include spaces or begin with numbers. Variable names are case sensitive: the names "Chickens" and "chickens" will be treated as different variables. Khmer script is permitted.
-   All variables should be numeric; including string or categorical data will result in errors or estimates that are difficult to interpret. Consider adding them to the app as grouping variables instead.

Two additional files, weights.csv and groups.csv, should follow the same file naming convention outlined above and are used to store the household-level weights and any categorical or grouping variables, respectively. Both files are optional; if they are not included, all data files should include weights and grouping criteria. If weights are not found, the numbers presented in the app will represent the unweighted (sample) totals and means.

### Adding New Variables, Creating Your Own Policy Goals, Setting Up Policy Pathways, and Determining Relevant Variables

The app will register all variables included in the input data files (see Diagnostics), but it will only incorporate the variables that have been included in the Update folder spreadsheets to avoid presenting too many options simultaneously.

### Policy Context

This page provides data and visualizations from both external sources and the CAS for understanding the agricultural and economic context in Cambodia. The Agricultural Sector Overview tab provides sector-wide information, while the Commodity Overviews provide information related to specific commodities. The colored **value boxes** provide statistics sourced from the World Bank's [Open Data repository](https://data.worldbank.org/). Additional indicators can be added by downloading the csv files from their respective pages and placed in the Extdata subfolder in the main app directory. New datasets will be discovered and included automatically.

The commodities tab includes information of interest for specific crops or livestock species. The categories can be customized by editing the folders in the "Commodities" subfolder of the "Extdata" folder. The names of these folders will be used to determine the titles of each tab. Images downloaded from elsewhere can also be included; edit the "image_information.csv" file in each commodity directory to edit the titles and captions for the images.

### Identifying Feasible Options

This page provides a way to view and consider policies to address a given policy goal.

Policy goals can be adjusted on the **Policy Instruments by Goal** tab to tailor the app to their preferences by editing the Policy_Pathways.csv spreadsheet in the Update folder or available as a direct download from the provided link. For each policy goal, develop a list of methods for achieving the goal, then determine the legal instrument that could be used to implement each method. Assess the instruments according to their effects on costs for producers (*Producer unit costs*), prices paid by consumers (*Final consumer price*), quantity of products exchanged in the market (*Final prod Q*), the quality of the product (*Prod quality*), and the relative time to implement the instrument by passing laws or creating policies (*Speed*). Additional notes for feasibility of implementation and the impacts of the existing trade and legal framework can be added, or you can add your own columns. The symbols ⬇, ⬆, ⬍ (used to indicate that a change is anticipated but the direction is ambiguous), = (no change anticipated), and ? (outcome for a non-directional criterion) will have special formatting applied; all others will be shown as plain text.

The **Stakeholder Mapping** tab displays diagrams of stakeholders in value chains that might be affected by new policies. Images created using diagramming applications are displayed here.

### Gather Evidence & Assess Data

This page allows users to summarize Cambodia Agriculture Survey data organized around the policy goal. The **Data Summaries** tab presents summary statistics and, when available, trends for variables relevant to each policy goal. The variables associated with each goal are set manually using the spreadsheets in the Update folder (see **Spreadsheet-Based Content Management**, above). The **Evidence from the Literature** tab shows a list of citations relevant to the policy goals and can be updated using the evidence_list.xlsx file in the Update folder.

To view estimates, begin by selecting a policy goal from the drop-down menu. Once a selection is made, the app will summarize all of the variables associated with that goal and present the Variable Summary Table and mapping options. Selecting a pathway will reduce the number of variables to just those identified as relevant to the policy instrument selected. The Mean/Total switch toggles between presenting national (or Zonal/Provincial) means to weighted totals.

Below the Variable Summary Table, the Detailed Information section, when expanded, shows sample sizes and other information saved as notes in the indicators spreadsheet.

##### Maps

A dropdown menu and a toggle switch will appear on the right side of the screen after a policy goal is chosen. The dropdown menu contains all the variables related to the policy/pathway, and the toggle switch can be used to swap between aggregation to the provincial level and the zone level. Selecting a variable will automatically draw the maps, the top showing the value from the latest available year, and the bottom showing the trend since the beginning of the survey series, when available. A third line plot shows the national-level trend since the beginning of the survey series.

##### Data Export

The table data can be downloaded as a csv file using the "Download Table Data" button. Maps can be saved by right clicking and saving the image, and the plot can be exported using the menu. The button with the `r shiny::icon("file-arrow-down")` symbol will download the data table for the first map.

### Interpreting Data Relationships

While the Gathering Evidence tab provides a general overview, the **Interpreting Data Relationships** page provides a more detailed look and side-by-side comparison of selected variables. This page can be used to visualize relationships between variables using a correlation heatmap. The heatmap shows the strength and direction of correlation between each pair of variables, with red indicating stronger positive correlations and blue stronger negative correlations. Hover over each dot to see the p-value of the correlation. Smaller values indicate stronger certainty that the association is not the result of chance variations in the data.

The organizational logic is the same as the Gather Evidence page, with options appearing after a policy goal is selected. Options to select two variables for a simple x-y comparison will appear, and those options can be narrowed further by selecting a policy pathway. A second button labeled "Show Heatmap" will also appear. Pressing this button will show a correlation heatmap across all the variables under the policy goal or the selected subset if a pathway is chosen.

All data processing will omit observations with empty or NA values for one of the variables, but the checkbox "omit 0s from Y variable" can be used filter the data further to include only observations where the selected Y variable has a non-zero value. This can be used to make the histograms easier to read or target a subpopulation of interest. For example, if the selected Y variable is "number of chickens vaccinated," the unmodified results would include all chicken owners who did not vaccinate any of their chickens, while omitting 0's would include results only for chicken owners who did vaccinate at least one chicken.

Data can also be grouped along subpopulations of interest. If a variable is included in the "groups.csv" spreadsheet in the raw data and has an entry in the "grouping_vars.xlsx" spreadsheet in the Update subfolder, it will appear in the list, and the results will compare values across the categories in that group.

Once you have selected variables and modifications, press the "Compare Variables" button to generate the graphs. Clicking the `r shiny::icon("table")` button above each histogram will show a table of the values (this table is omitted when viewing results at the household level due to the large number of entries it would have). A scatter/line graph at the bottom provides a quick assessment of the degree of correlation between the selected variables using a linear model. While this is not a substitute for rigorous statistical analysis, it can provide information about hypothesized relationships between variables that can be explored further using R or another statistical package using the raw data.

##### Data Export

Data can be downloaded in one of three ways:

-   The "Download Selected Raw Data" will provide observations **for only the variables selected in the dropdown boxes**. The optional selections (omitting 0's, administrative level, and grouping variables) will be honored in the data; therefore, selecting a level other than household will provide a summarized dataset.

-   The "Download All Listed Raw Data" will provide the export format as above, but for **all of the variables related to the selected policy goal and pathway**.

-   The buttons with the `r shiny::icon("file-arrow-down")` symbol will provide an spreadsheet version of the data table (for zone- and province-level summaries) with in a format that can be read by the app to reproduce the table on the **Policy Context** page if the file is placed in the proper commodity folder. Do not change the name of the file when using this feature.

### Additional Considerations & Sources for Evaluating Options

This page provides links to associated sources of data and information that can be used to create further figures. Edits to this table can be made by editing the Secondary_Sources.csv spreadsheet.

### App Diagnostics

In addition to the instructions you are currently reading, this page provides the **App Diagnostics** tab, which can be used to troubleshoot if the app stops working after an update. The app will check that the data and supporting spreadsheets are present and correctly formatted with the expected column names. In addition, it will present all of the variables found in the data files and report whether the metadata needed to incorporate them into the app are present. For a variable to show up, it must at least be present in the indicators list and be assigned to a policy goal. Assignment to a pathway is optional. Note that this is not the case for the hhid, province, and zone variables, which are used to identify observations. They should be present in all of the data files with the exception of groups and weights, which need only the unique household id.

