---
title: "Changelog"
author: "Andrew Tomes & Haley Skinner"
output: html_fragment
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### 06/16/23 (v0.2.0-beta)
* Updates
  * Inclusion of "all" observations while disaggregating for better comparison (i.e. disaggregation by gender of household head now produces "Male", "Female", and "All")
  * Inclusion of SSP (small scale producer household) to filter set
  * Fixed bugs with data (i.e. household crop production errors, household income data)
  * Fixed bugs with data exports, data distribution plotting
  * Improved layout of mapping section
* Changes
  * Revised interface of Input tab


### 02/13/23 (v0.1.8-beta)
* Updates
  * Fixed issue with mapping section caused by the renaming of a variable
  * Updated graphing section to allow indicators to be on the x axis.


### 02/01/23 (v0.1.7-beta)
* Updates
  * Stealth 0.1.6 update meant to include Tanzania still on hold while we wrap up backend LSMS coding.
  * Minor modifications to NGA data; yield continues to be difficult to track for wave 4 due to uncertainties around land area; restricting to GPS-measured plots is currently the best remedy (GPS measurement appears to have differential impacts on yield depending on your crop - roots and tubers have substantially higher yields on unmeasured plots, while corn and legumes are lower).
  * The gps_area variable is now available in all NGA waves. 
  * Fixed a bug that was causing weights to be incorrectly computed for some variables. 
  * Fixed a bug that was causing duplicated entries in the raw data export; your workbook may have multiple sheets for variables that have different units of observation.
* Changes
  * Major update to charting section for a better data visualization experience
  * Crop disaggregation is now handled differently for a (hopefully) more intuitive user experience.
  * There is now a setting under the advanced options for restricting to panel households. If you get a "no data" error, it might be because a panel refresh happened between two of the waves in your selection.
* Known Issues
  * Depending on your browser's settings, the raw data may download in the background.
  * It's still possible to generate crop-specific indicators (e.g., yield, area planted) without specifying a crop disaggregation. The estimates produced by doing so may or may not be coherent. Please take care when interpreting results that include multiple crops.
  * The changes for labor accounting in Nigeria wave 4 result in significantly lower estimates of total labor days worked, and, consequently, labor productivity is substantially higher. I think this is an artifact of instrument design and not the result of shifting labor patterns. 
  

### 02/15/22 (v 0.1.5-beta)
* Updates
  * Added an experimental set of estimates for MPI sub-dimensions and food and water access in Nigeria W4.
  * Connected to google analytics
* Changes
  * Raw data is now exported as a single file
  * Fixed a bug that was causing analysis to terminate early if the first variable selected wasn't in the target survey(s)
  * Improvements to mapping
  * Modifications to the data distribution section to improve readability and presentation.
* Data
  * Plot variables can be filtered by whether the plot was measured by GPS (currently available for NGA W4 only)
  * Fixes for crop yield and expense estimates for NGA W4 (still in progress)

### 11/29 (v 0.1.4-beta)
* Updates
  * Some back-end changes to smooth how selection by geography works. 
* Changes
  * Prepped the geographical aggregation section for additional countries
  * Fixed absence of identifying information in raw data export
  * Fixed a bug that was causing the program to bypass checking whether a user had selected a dataset
  * Updated units for some variables to improve clarity
* Known Issues
  * ~~As the added note says, caching raw data for export can add a lot to the app's RAM usage. Fixes pending.~~

### 11/22
* Updates 
  * Added versioning; this update tagged as 0.1.3-beta
  * Implemented dynamic query construction
  * Data table now has medians in addition to means
  * Implemented raw data export
* Data
  * Household-level income and livestock variables actually work now.
* Known Issues
  * ~~Raw data export lacks identifying/geographical information for entries.~~

### 11/16
* Updates
  * Implementation of EA/LGA mapping
* Changes
  * Fixed mapping section to allow maps to display at larger sizes
  * Removed "Distance to Ag Market" filter criterion (not implemented on the back end yet)
* Data
  * Added EA/LGA coordinates to data files

### 11/9
* Public Beta release v0.1
  * Known issues/things that are currently in the works as this goes live:
    * ~~User interface will be updated to allow dynamic query construction using drop-down boxes~~
    * ~~Graph resolution and size are still a little weird~~ 
    * ~~EA and LGA plotting are still a work in progress~~
    * If you encounter other bugs or have other feature requests, please let me know


### 9/22
* Updates
  * Indicator and grouping variable metadata are now functional and available for download.
  * It's possible to group data at below-country level (not at above-country level yet, though)
  * Graphing now produces box plots for people who want to look into things below the country level.
* Changes
* Data
* Known Issues
  * Fixed a bug that was causing the commodity grouping code to misclassify crops

### 9/21
* Updates
* Changes
* Data
* Known Issues
  * ~~The latest update to the Stata side of the code accidentally resulted in dropping grouping variables, so now the grouping is broken.~~ Fixed 9/22

### 9/20
* Updates
* Changes
  * Added spreadsheet for grouping category definitions and to improve display on the data tables
  * Cleaned code and packaged app into a single file to facilitate containerization. Ready for server deployment!
* Data
* Known Issues


### 9/17
* Prepared app for containerization with Docker

### 9/16
* Updates
* Changes
* Data
* Known Issues
  * ~~The way geography is handled right now results in weird plot captions. WIP.~~ (Fixed)

### 9/15
* Updates
  
* Changes
  * Edits to crop filtering section of the interface
  * Added rug plot to the distribution plots.
  * Changed plotting so it automatically switches to bar chart when there is only one year selected (having multiple countries will cause issues).
  * Added a "Pretty name" to the variable sheet for labels.
  
* Data

* Known Issues
  * ~~Female-headed household designator missing from NGA W2~~ Fixed.
  

### 9/14
* Updates
  * I introduced a filterset spreadsheet that can be used to define filters through excel so that we don't have to go into the app to redefine them. I wrote a small script at the beginning that takes the household file and cuts it down to the filters on the spreadsheet to save on resource use during runtime, but it only runs if it can't find the relevant files. If you update the spreadsheet, be sure to delete the <country>_<wave>_filterset.dta file so that it re-makes it. Otherwise you'll get a "Filter criterion not found" error.
  * Added basic demographic indicators
  
* Changes
  * Added SSP grouping criterion

* Data
  * Lots of 0's for kgs harvest in W4 - check to make sure they aren't being artificially introduced.
  * Still some suspiciously high values for crop expenses
  

* Known Issues
  * The program is getting increasingly RAM-hungry, especially with the introduction of the distribution plots. One of the unfortunate consequences of being able to dynamically generate datasets is that we end up with a lot of data that need to be held in memory until the session ends or the user sends a new request. 
  * ~~The variable "farm_size_agland" is still showing up in places where it shouldn't~~ (Fixed)
  * Need a reset button for main options
  * ~~The ag household filter doesn't actually do anything yet~~ (Done!)
  * ~~Still need to include variable descriptions~~ (Done 9/15)


### 9/13
* Updates
  * Chart export is now available.  
  * Filtering by administrative level is now functional (note: going down to small units can create seriously messy graphs and suck up system resources; also, administrative levels will need to be harmonized across countries to ensure program runs correctly)

* Changes
  * Updates to UI to include filtering, improve screen real estate usage
  * Implemented raincloud plots on the data distribution tab

* Data
  * ~~Crop expenses for NGA W2 appear to be compiling incorrectly (labor valuations are still off?)~~
    * Values are being pulled up by a few extreme results; winsorizing should take care of this issue. Some labor expenses are high because the number of labor days seems off (>365 days)
  * Need to double check palm oil conversions in W4 to make sure they're working correctly
  * In general, plot data is very swingy and sensitive to outlier data, even with winsorizing. Crop expenses look weird for W3, and inorganic fertilizer rate looks weird for W2. Need to fix.
  
* Known Issues I'm Currently Working On
  * ~~I'm not 100% sure the inflation correction is working.~~ (Fixed)
  * ~~Family labor days are not being picked up when requested~~ (Fixed 9/22)
  * Lots of 0's for kgs harvest in W4 - check to make sure they aren't being artificially introduced.
  * ~~Winsorization code doesn't work properly when custom ranges are used~~ (Fixed)
  * ~~Data distribution graphing isn't particularly helpful~~ (Addressed?)
    * Changed from box plots to raincloud plots. The large sample sizes mean that things took a while to render and the dot plot portion obscured the box plot. I removed dot plots for now but can add them back in.
  * ~~Data tables will periodically decide not to render~~ (Fixed)
  * ~~The variable "farm_size_agland" is used both as an indicator and a source of filtering criteria, causing it to show up multiple times in the results.~~ (Fixed)
  * Need a reset button for main options
  * ~~The ag household filter doesn't actually do anything yet~~